### ISSUE TITLE
Kan niet inloggen

### ISSUE THREAD

**Issue by git-snurger** [MrTwixxy/MagiWatch#1]
Als ik probeer in te loggen in de MagiWatch telefoon app, gebeurt er niks. Ik heb honderden keren proberen opnieuw in te loggen alleen niks werkt. Fix zou heel fijn zijn!

**Comment by MrTwixxy** [comment]
Zou je me eens stap voor stap uit kunnen leggen hoe je probeert in te loggen?

Je moet zorgen dat de app is geïnstalleerd op je horloge en de telefoon waarmee je horloge verbonden is. Let wel op dat de apk voor je horloge een andere is dan voor je horloge. 

Als je de juiste apps hebt geïnstalleerd kan je in de app op je telefoon een inlog knop zien en staat er op je horloge de tekst "Login met MagiWatch connect"

Als je dan de beide apps open hebt en de twee apparaten verbonden zijn met elkaar via Bluetooth zou de horloge app tot leven moeten komen na het inloggen op je telefoon.

**Comment by git-snurger** [comment]
Ik heb de APK's correct geinstalleerd en mijn telefoon en horloge zijn verbonden met elkaar. Als ik in de app op mijn telefoon op de 'Verbinden met Magister' knop onder mijn horloge klik, en ik log in, gebeurt er niks. De knop blijft, hij verbind niet en op mijn horloge verandert ook niks.

**Comment by MrTwixxy** [comment]
Wat is het model van je horloge?

**Comment by git-snurger** [comment]
Ik heb een Fossil Gen 5 Carlyle HR

**Comment by MrTwixxy** [comment]
Normaliter word je na het inloggen in de mobiele app inderdaad gewoon terug gestuurd naar de homepagina en blijft de knop actief, maar er zou een laadicoontje moeten verschijnen op de horloge en even later verschijnt dan daar je agenda. 

Als er helemaal geen laadicoon verschijnt ontvangt de horloge überhaupt geen data van de mobiele app, maar waar in de connectie het dan precies mis gaat durf ik niet te zeggen.  



Heb je ooit de app Gemairo gebruikt? Dat is een app (gewoon voor je telefoon) om statistieken en grafiekjes te zien van je Magister cijfers, grotendeels van de login logica is overgenomen vanuit de source code van die app, dus je zou kunnen proberen of inloggen in die app wel werkt, dan weet je zeker of het aan het inloggen ligt of aan de connectie met je horloge.

**Comment by git-snurger** [comment]
Bij Gemairo werkt het wel, alleen ik weet bijna zeker dat het niet aan de connectie ligt aangezien het bij apps zoals WearMedia Musik Player wel werkt.

**Comment by MrTwixxy** [comment]
Dan weet ik eerlijk gezegd niet waar het door komt. 
Ik heb zelf een Galaxy Watch (en mijn vrienden ook) en daarbij werkt alles gewoon zonder problemen...

**Comment by git-snurger** [comment]
Jammer!
